[settings]
status.missing_tools = "always"
sops.rops = false

[env]
_.file = [".env", ".env.development.yaml", ".env.local"]
_.path = ["./node_modules/.bin", "./bin"]

[tools]
node = "20.18.0"
shellcheck = "0.10.0"
sops = "3.9.4"
age = "1.2.1"
jq = "1.7.1"
rust = "stable"
