[settings]
status.missing_tools = "always"
sops.rops = false

[env]
_.file = [".env", ".env.development.yaml", ".env.local"]
_.path = ["./node_modules/.bin", "./bin"]

[tools]
node = "22.16.0"
shellcheck = "0.10.0"
sops = "3.10.2"
age = "1.2.1"
jq = "1.8.0"
rust = "stable"
