services:
  database:
    image: mysql:8.0.31
    environment:
      MYSQL_DATABASE: ptat
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
