services:
  database:
    image: postgres:16.2
    environment:
      POSTGRES_USER: ptat
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
