name: deploy
on:
  pull_request:
    branches:
      - main
    types:
      - closed
concurrency:
  group: ${{ github.workflow }}
jobs:
  deploy:
    name: Deploy
    environment:
      name: Production
      url: https://ptat.example.com
    # TODO: remove github.repository check, you don't need it (it's just here to prevent the template repo itself trying to deploy)
    if: |
      ${{
        github.repository != 'pentible/typescript-app-template' &&
        github.event.pull_request.merged
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      # update db
      - name: Install pscale
        uses: planetscale/setup-pscale-action@v1
      - name: Update db
        env:
          PLANETSCALE_ORG: ${{ vars.PLANETSCALE_ORG }}
          PLANETSCALE_SERVICE_TOKEN_ID:
            ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
        run: ./bin/dev ci db migrate prod

      # decrypt env
      - name: Install sops
        uses: mdgreenwald/mozilla-sops-action@v1.5.0
      - name: Decrypt environment variables
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: |
          envs="$(
            sops --decrypt --output-type json .env.production.yml \
            | jq --compact-output 'with_entries(.key |= sub("_unencrypted$"; ""))'
          )"
          echo "APP_ENVS=${envs}" >> "$GITHUB_ENV"

      # deploy
      - name: Deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ github.event.repository.name }}
        run: |
          readarray -t env_lines < <(jq --raw-output 'to_entries[] | "\(.key)=\(.value)"' <<< "$APP_ENVS")
          declare -a args=()
          for env_line in "${env_lines[@]}"; do
            args+=(-b "$env_line" -e "$env_line")
          done

          vercel --token="$VERCEL_TOKEN" deploy --prod "${args[@]}"
