name: lint
on:
  # NOTE: The ref for pull request triggered events defaults to
  # `refs/pull/<pr-number>/merge`, this is essentially the virtual merge ref
  # that would be created if the pr was merged. This means your linting checks
  # actually gives you a much better idea of whether the linting will pass once
  # merged.
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - env:
          COLOR: 1
          FORCE_COLOR: 1
        run: |
          mise run \
          --continue-on-error \
          --output keep-order \
          lint
