name: preview-close
on:
  pull_request:
    branches:
      - main
    types:
      - closed
concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true
jobs:
  preview-close:
    name: Close preview
    # TODO: remove github.repository check (and NOT the merged check), you don't need it (it's just here to prevent the template repo itself trying to deploy)
    if: >
      github.repository != 'pentible/typescript-app-template' &&
      !github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Delete Preview Branch
        uses: neondatabase/delete-branch-action@v3.1.3
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          api_key: ${{ secrets.NEON_API_KEY }}
          branch: |-
            preview/pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}
