name: preview-close
on:
  pull_request:
    branches:
      - main
    types:
      - closed
concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true
jobs:
  preview-close:
    name: Close preview
    # TODO: remove github.repository check, you don't need it (it's just here to prevent the template repo itself trying to deploy)
    if: |
      ${{
        github.repository != 'pentible/typescript-app-template' &&
        !github.event.pull_request.merged
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pscale
        uses: planetscale/setup-pscale-action@v1
      - name: Close preview
        env:
          PLANETSCALE_ORG: ${{ vars.PLANETSCALE_ORG }}
          PLANETSCALE_SERVICE_TOKEN_ID:
            ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
        run: ./bin/dev ci db close preview
